### ISSUE TITLE
Problems with unicode

### ISSUE THREAD

**Issue by Teddytrombone** [phpactor/phpactor#2529] opened 2024-02-02 15:54 UTC
Phpactor does not seem to correctly work with various unicode characters. Some characters raise exceptions and "position aware" features like diagnostics have wrong positions.

Example PHP code:

```php
<?php

echo '👩🏽‍👨🏽‍👦🏽‍👧🏽 ' . invalid() . strlen('Lorem ipsum dolor sit amet');
```

Phpactor shows the following error when requesting completion:

```
Request textDocument/completion failed.
  Message: Exception [RuntimeException] preg_replace could not parse string (size 49): Malformed UTF-8 characters, possibly incorrectly encoded at dantleech.vscode-phpactor/phpactor/lib/Completion/Core/Util/OffsetHelper.php#15
  Code: -32603 
#0 dantleech.vscode-phpactor/phpactor/lib/Completion/Bridge/TolerantParser/WorseReflection/DoctrineAnnotationCompletor.php(95): Phpactor\Completion\Core\Util\OffsetHelper::lastNonWhitespaceCharacterOffset()
#1 dantleech.vscode-phpactor/phpactor/lib/Completion/Bridge/TolerantParser/WorseReflection/DoctrineAnnotationCompletor.php(38): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\DoctrineAnnotationCompletor->truncateSource()
#2 dantleech.vscode-phpactor/phpactor/lib/Completion/Core/ChainCompletor.php(25): Phpactor\Completion\Bridge\TolerantParser\WorseReflection\DoctrineAnnotationCompletor->complete()
...
```

Furthermore the red underlines because of the unknown function `invalid` are at the wrong position.

VS Code:
![image](https://github.com/phpactor/phpactor/assets/14216933/b0656319-7bbc-4b2e-8517-be4bf5ff9c35)

Neovim:
![image](https://github.com/phpactor/phpactor/assets/14216933/5e6691eb-a8d1-4bc0-bd87-13f6c9eadbb3)

**Comment by dantleech** [comment] 2024-02-03 20:41
honestly I'm just confused, this is the code responsible for this:

https://github.com/phpactor/phpactor/blob/1419d7137d5ead44b2f4d3ad3d15152792bb46d0/lib/Extension/LanguageServerBridge/Converter/PositionConverter.php#L32

the specification says:
![image](https://github.com/phpactor/phpactor/assets/530801/cd4c4aa0-d67d-4d39-89cc-2215d3a4a5c3)

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/

---

Currently we return the character offset as the number of _bytes_ i.e. `strlen($truncatedStringAtPosition)` - which maps to UTF-8 encoding (if I understand correctly).

Possibly this is caused by Neovim using UTF-16 instead of UTF-8 as I'm sure this worked once.

Anyway, the solution is probably to calculate the number of "16 bits" used in the string - or to tell Neovim to use UTF-8.

I'd test this hypothesis, but my brain is fried.

**Comment by dantleech** [comment] 2024-02-03 23:55
Can  you test this PR: https://github.com/phpactor/phpactor/pull/2530  and let me know if it fixes your issue?

**Comment by dantleech** [comment] 2024-02-04 00:04
related https://github.com/phpactor/phpactor/issues/1601 and https://github.com/phpactor/phpactor/issues/1391

**Comment by Teddytrombone** [comment] 2024-02-04 18:04
Yes, the PR solves my issues both in VS code and neovim. No exception is thrown while requesting completions and the error "underline" ist on the correct position.
Thank you!

**Comment by dantleech** [comment] 2024-02-04 18:24
cool, merged :)

**Comment by dantleech** [comment] 2024-02-04 18:26
the preg_replace error is still there however, so keeping this open

**Comment by Teddytrombone** [comment] 2024-02-04 18:56
Yes, you are right. Sorry, I did my test at the wrong place (at end of the line) and just had a look, if the exception was thrown. When triggering completion right after the string containing the emoji, the exception gets thrown.

**Comment by dantleech** [comment] 2024-02-04 22:40
For reference the error is the same problem in reverse:

https://github.com/phpactor/phpactor/blob/master/lib/Extension/LanguageServerBridge/Converter/PositionConverter.php

(i.e. converting a UTF-16 LSP position to a Phpactor byte offset)

**Comment by Teddytrombone** [comment] 2024-02-10 17:32
I dug a bit deeper into the code. Maybe I'm wrong (I am very far away from fully understanding how phpactor works), but wouldn't there be much more problems regarding UTF-16 "positions"? For example in `\Phpactor\TextDocument\LineCol` - when an instance is created because of a client to server request, the "col" parameter of the constructor is a position based on UTF-16. But when instantiated because of a phpactor functionality like `\Phpactor\TextDocument\Util\LineColRangeForLine` or even `\Phpactor\Extension\LanguageServerBridge\Converter\PositionConverter::byteOffsetToPosition` the "col" parameter is a position based on UTF-8, so the returned position to the client would be wrong in some cases (allthough it is fixed in PositionConverter). I don't even know if there are more locations, where a encoding mismatch based on positions could trigger problems. LineCol was just one thing, I stumbled upon first ;-)

Just thinking loud: wouldn't it be easier to handle positions on a lower level? So when receiving or sending a Position, it is converted back and forth "automagically" by a middleware. Everything "inside" phpactor can then act as if everything is UTF-8. I don't even know, if this would make any difference to the preg_replace error.
And as I said, with my lack of knowledge, I have no idea at the moment, if a middleware is the correct place to put something like this. Maybe I'm completly wrong. If so please ignore my comment ;-)

**Comment by dantleech** [comment] 2024-02-24 13:23
ok, i think this one should do it: #2557

**Closed** 2024-02-24 13:26 UTC
