### ISSUE TITLE
Incorrect type inference

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1770] opened 2022-07-12 14:34 UTC
<img width="465" alt="image" src="https://user-images.githubusercontent.com/12109622/178515264-e2536ede-8146-490e-8c9a-db13f75e6459.png">
<img width="706" alt="image" src="https://user-images.githubusercontent.com/12109622/178515322-de568411-7958-40c9-83b5-55f26232d683.png">
The error says:

```
Method "getId" does not exist on class "Doctrine\Common\Collections\Collection<int,MarsIPM\Entity\StakeholderAssessment>"
```
The type of `$analysis->getStakeholders()` is `Doctrine\Common\Collections\Collection<int,MarsIPM\Entity\StakeholderAssessment>` and therefore the type of `$analysis->getStakeholders()[0]` is `MarsIPM\Entity\StakeholderAssessment` which has the method in question.

**Comment by dantleech** [comment] 2022-07-12 17:00
I think duplicate of this ticket: https://github.com/phpactor/phpactor/issues/1593 reopen if not :)

**Closed by dantleech** 2022-07-12 17:00 UTC
