### ISSUE TITLE
`textDocument/references` returns same position for start and end

### ISSUE THREAD

**Issue by smjonas** [phpactor/phpactor#2064] opened 2023-01-30 20:41 UTC
Originally reported as an issue on this Neovim plugin repo: https://github.com/smjonas/inc-rename.nvim/issues/30

When sending a `textDocument/references` request for a given identifier, the server always responds with a result like this (formatted as a Lua table):
```lua
{
    range = {
      ["end"] = {
        character = 8,
        line = 15
      },
      start = {
        character = 8,
        line = 15
      }
    },
    uri = "file:///some_file.php"
 }
``` 
Notice how the `start` and `end` characters are the same.

## Expected result
```lua
{
    range = {
      ["end"] = {
        character = 11, -- (assuming the variable is 4 characters long)
        line = 15
      },
      start = {
        character = 8,
        line = 15
      }
    },
    uri = "file:///some_file.php"
 }
```

**Comment by dantleech** [comment] 2023-01-30 21:09
confirmed, thanks for reporting :+1:

**Comment by dantleech** [comment] 2023-02-06 21:32
For reference it's because the underlying implementation does not record the "end" positions of the references, could be fixed by working back from here: https://github.com/phpactor/phpactor/blob/ab023ca8143a5253673d394cb255ec1420094b45/lib/Extension/LanguageServerBridge/Converter/LocationConverter.php#L43

**Comment by mamazu** [comment] 2023-10-26 21:58
Can be closed as the feature made it into the master. :partying_face:

**Comment by dantleech** [comment] 2023-10-26 22:10
🎉

**Closed** 2023-10-26 22:09 UTC
Labels: bug
