### ISSUE TITLE
Local variable hint is displayed over the definition, rather than the reference it's initiated on

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1221] opened 2021-03-15 14:13 UTC
In the following scenario (the mouse is on the red circle):
![image](https://user-images.githubusercontent.com/12109622/111166732-113b5380-85a9-11eb-8507-c56f28c7373d.png)

the hint is displayed on the definition up on the screen. The problem with that is (except it is in the wrong place), when the definition is not visible, the hint just flashes on the screen.

**Comment by dantleech** [comment] 2021-03-15 14:27
![image](https://user-images.githubusercontent.com/530801/111168951-7471b980-859a-11eb-9b87-d8e356fb7229.png)

Can reproduce - strange it doesn't happen in VIM though:

![image](https://user-images.githubusercontent.com/530801/111169014-82273f00-859a-11eb-8ee0-293aebebd6bd.png)

**Comment by BladeMF** [comment] 2021-03-15 14:28
I probably need to check the actual response from the request, but I am so short on time...

Vladi.
________________________________

**Comment by BladeMF** [comment] 2021-03-15 14:28
I also don't think it is every time, there is something specific in that example, but can't figure out what.

Vladi.
________________________________

**Comment by BladeMF** [comment] 2021-03-22 14:28
By the way, we should probably find what's wrong with the formatting of the "Frame" in VS Code.

**Comment by dantleech** [comment] 2021-03-22 14:43
There's nothing wrong with it, it's just :hankey: :smile:

**Comment by BladeMF** [comment] 2021-04-13 07:05
I actually played with the formatting of these Twigs quite a lot, I will share the result at some point. :-)

**Comment by BladeMF** [comment] 2021-04-26 07:30
So the problem causing that bug is that the code:
```
$offsetReflection = $this->reflector->reflectOffset($document, $offset);
$symbolContext = $offsetReflection->symbolContext();
```
`$symbolContext->symbol()->position()`, which `HoverHandler` is using (that's why it's not happening in VIM, btw), returns the position of the definition, not the reflected offset. Not sure how to fix. If you can provide relevant code and/or solution, @dantleech?

Currently the workaround is to change that:
```
            return new Hover($string, new Range(
                PositionConverter::byteOffsetToPosition(
                    ByteOffset::fromInt($symbolContext->symbol()->position()->start()),
                    $document->__toString()
                ),
                PositionConverter::byteOffsetToPosition(
                    ByteOffset::fromInt($symbolContext->symbol()->position()->end()),
                    $document->__toString()
                )
            ));
```
to
```
            return new Hover($string, new Range(
                $position,
                $position,
            ));
```
in `Phpactor\Extension\LanguageServerHover\Handler\HoverHandler`.

**Comment by dantleech** [comment] 2021-04-26 16:15
> If you can provide relevant code and/or solution, @dantleech?

It's in Worse Reflection, maybe [here](https://github.com/phpactor/worse-reflection/blob/5f138ad936cd37d88bb10e01adad45334472241b/lib/Core/Inference/SymbolContextResolver.php#L771) or [here](https://github.com/phpactor/worse-reflection/blob/5f138ad936cd37d88bb10e01adad45334472241b/lib/Core/Inference/FrameBuilder/AssignmentWalker.php#L145). Basically those positions are being assigned from the definition instead of the instance somewhere...

**Comment by dantleech** [comment] 2022-09-10 15:59
Cannot reproduce this now, can you confirm? Otherwise closing.

**Closed by dantleech** 2022-09-10 15:59 UTC
