### ISSUE TITLE
GotoDefinition failing

### ISSUE THREAD

**Issue by FatBoyXPC** [phpactor/phpactor#233] opened 2017-10-15 08:13 UTC
I'm in a laravel app, and when I try to GotoDefinition on `PartnerOnboarding::findByCode()` with my cursor on 'findByCode', I get this:
`Phpactor: Containing class for member "findByCode" could not be determined`.

I do have `use PartnerOnboarding` just below my namespace, and when I GotoDefinition with my cursor on `PartnerOnboarding` on that same line, it finds that class just fine!

**Comment by dantleech** [comment] 2017-10-15 09:18
Goto definition works for me on static methods - can you debug and paste the results of the following?

```
$ phpactor offset:info /path/to/yourFile.php <offset> --verbose
```

The `<offset>` can be determined by hitting `g` then `<ctrl-g>`, which should show something like:

```
Col 5 of 107; Line 15 of 28; Word 27 of 58; Byte 606 of 1033
```

Here 606 is the offset...

**Comment by FatBoyXPC** [comment] 2017-10-21 04:09
It's fairly weird it is having problems resolving this. I do realize Eloquent utilizes some magic methods sometimes, but this isn't one of them. This method is defined in the same class just 17 lines before I'm calling it:

```
    public static function findByCode($code, $fail = true)
    {
        $partner = self::where('code', $code);

        return $fail ? $partner->firstOrFail() : $partner->first();
    }
```

Anyway, here's the offset information:

`Col 23 of 45; Line 87 of 353; Word 220 of 775; Byte 2487 of 9721 `

```
➜  dm20 git:(master) ~/.vim/bundle/phpactor/bin/phpactor offset:info ~/dev/dm20/app/Models/PartnerOnboarding.php 2487 --verbose
[2017-10-21T04:04:18.383130+00:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Statement\ClassDeclaration [] []
[2017-10-21T04:04:18.384193+00:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Parameter [] []
[2017-10-21T04:04:18.384223+00:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\ReservedWord [] []
[2017-10-21T04:04:18.384374+00:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\TernaryExpression [] []
[2017-10-21T04:04:18.384402+00:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\Variable [] []
[2017-10-21T04:04:18.384543+00:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\Variable [] []
[2017-10-21T04:04:18.384766+00:00] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\ScopedPropertyAccessExpression [] []
[2017-10-21T04:04:18.396662+00:00] phpactor.WARNING: Could not find source with "Eloquent" [] []
[2017-10-21T04:04:18.396711+00:00] phpactor.DEBUG: Resolved type "<unknown>" for method "findByCode" of class "PartnerOnboarding" [] []
symbol:findByCode
symbol_type:method
start:2482
end:2492
type:<unknown>
class_type:
value:NULL
offset:2487
type_path:
class_type_path:
➜  dm20 git:(master) 
```

**Comment by dantleech** [comment] 2017-10-21 06:34
```

**Comment by FatBoyXPC** [comment] 2017-10-21 06:45
Yeah, so it's because `PartnerOnboarding` extends `BaseModel`, which extends `Eloquent` which after looking at this project's composer file, I have no idea how that gets resolved cleanly. Oh well, I won't question it. I think it's safe to mark this as closed since this is clearly a fault of this project, not your amazing plugin!

[Language Server Protocol](https://github.com/Microsoft/language-server-protocol) - I believe it was created for VS Code, but open source, and there are several implementations of the client now (vim8 and neo-vim both have language server clients).

**Comment by dantleech** [comment] 2017-10-21 07:02
Ah yeah, it's using the parser microsoft developed for VS/LSP, but otherwise everything else is home grown :)

Can you see where `Eloquent` is found? (e.g. `find ./ -name "Eloquent.php"` for example). I started working on a new locator which can find things in non-standard locations, would be good to know if it covers this case.

**Comment by FatBoyXPC** [comment] 2017-10-21 07:15
Oh, awesome! Any idea how PHP Storm is doing it, since they had this before LSP came out?

Okay, so things are about to get confusing, and researching this has thrown me for quite a loop.

That find didn't find anything. However, this isn't surprising as I expected Eloquent to be a vendor file. So before I ran the find, i went off to the laravel 5.2 [repo](https://github.com/laravel/framework/tree/5.2/src/Illuminate/Database/Eloquent) looking for `Eloquent.php`, but alas, it's `Model.php`. Now I'm really curious how `class BaseModel extends Eloquent` doesn't blow up. I'm terrible with find syntax, but I imagine it's recursive by default and doesn't skip `vendor/`?

**Comment by dantleech** [comment] 2017-10-21 07:38
> Any idea how PHP Storm is doing it

PHPStorm, and just all other auto-completion/intellisense things handle this by creating an large index/database, parsing each file in the source tree. Phpactor does everything in real-time, and works in 90% of cases (depending on the project), but I may add an indexing option later. 

> I'm terrible with find syntax

Maybe just `grep -Rn 'class Eloquent'` ?

Or point me to something I can download from github?

**Comment by FatBoyXPC** [comment] 2017-10-21 07:54
So I know that PHP Storm isn't doing this like ctags, whereas Sublime's PHP Companion does. I both like and dislike ctags at the same time. It's great for obscure enough method names, terrible for method names such as `$foo->get()`.

Is this code aware of methods going through magic methods (such as `__call()` and `__callStatic()`)? If so, oh man this is going to put PHP Storm in the dust :joy: 

Regarding grep:
I did this in the project I started this issue with, and I found 2 partial matches, so clearly not what we want. Then I ran that command on a server I have with a 3 year old project (my first ever laravel project :smile:) and again, it only found a partial match. [This](https://github.com/csnades/website) is a link to that project if you'd like to clone it and what not. Be gentle, that was my first project, remember :laughing: I'm actually curious if the thing still builds or not (composer install, etc). I don't see why it wouldn't, I guess. If for whatever reason you can't get it to work locally, PM/email me and I am willing to give you access to the server to poke around if you want (with csnades, not the first app that I mention which is my work app).

**Comment by dantleech** [comment] 2017-10-24 06:21
The problem is that Laravel is using it's own autoloader and "class aliases", so the Laravel autoloader expands `Eloquent` to the fully qualified clashich s name.

So, it should be possible to support this (and other similar mechanisms) with some hackery (intercepting the autoloader).

**Comment by FatBoyXPC** [comment] 2017-10-24 15:04
Oh wow. I thought there was some class alias magic going on there, and
thought I investigated all of it - apparently not! Is doing some hackery
specifically for Laravel a good idea, here? Not that I would complain since
my daily job is on Laravel!

**Comment by dantleech** [comment] 2017-10-24 15:27
no, not especially for Laravel, it would work more generally than the current solution...

**Comment by FatBoyXPC** [comment] 2017-10-25 00:37
I think a friend of mine is having a similar issue with Yii :disappointed:

**Comment by dantleech** [comment] 2017-12-04 20:49
Closing this in favor of #281

**Closed by dantleech** 2017-12-04 20:49 UTC
