### ISSUE TITLE
Crash in some context

### ISSUE THREAD

**Issue by ging-dev** [phpactor/phpactor#1849] opened 2022-08-07 09:03 UTC
```php
<?php

class A {
    public static $id;

    public function getId() {
        return static::$<>
    }
}
```

```php
<?php

function foo(i<>)
{

}
```

**Comment by dantleech** [comment] 2022-08-07 20:22
hm, I don't get crashes in either case:

in the first case I don't get completion (it works without `$`):

![image](https://user-images.githubusercontent.com/530801/183309673-aacbaec5-2f77-41e9-8847-6af03327cc54.png)

And in the second case it works as expected:

![image](https://user-images.githubusercontent.com/530801/183309664-0757bf9e-eaad-4657-9fe2-b7abc4d94892.png)

**Comment by dantleech** [comment] 2022-08-07 20:23
hm, in VS code I get a crash however...

**Comment by dantleech** [comment] 2022-08-07 20:39
Should be fixed in https://github.com/phpactor/phpactor/pull/1850

The best way to fix this type of error would be to fix the type documentation in [tolerant parser](https://github.com/microsoft/tolerant-php-parser) as that would cause PHPStan to highlight all the places in Phpactor where this sort of thing could happen.

**Comment by dantleech** [comment] 2022-08-07 20:42
Feel free to continue discussion / reopen if still an issue.

**Closed** 2022-08-07 20:42 UTC

**Comment by ging-dev** [comment] 2022-08-09 12:04
> Feel free to continue discussion / reopen if still an issue.

There are still a few cases that break lsp on vscode
```php
<?php

use A<>
```

```php
<?php

use AB;

AB<>
```

**Comment by dantleech** [comment] 2022-08-12 07:45
i'm not very available at the moment (on a cycling holiday), but would be happy to review any fix for this. it is almost certainly because the parser returns NULL in these cases and it should be easy to ix.

**Comment by dantleech** [comment] 2022-09-09 12:00
You previous comment should now have been fixed (unrelated regression)
