### ISSUE TITLE
Dev dependencies are required

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#1281] opened 2021-05-25 12:31 UTC
When installing phpactor with no dev-deps (`composer install --no-dev`), the command `phpactor extension:list` (among others) can't be run, as it complains a class in a dev dependency is missing :

```
PHP Fatal error:  Uncaught Error: Class "SebastianBergmann\Diff\Differ" not found in ~/.config/nvim/pack/packager/opt/phpactor/lib/Extension/CodeTransformExtra/Command/ClassTransformCommand.php:34
```

installing dev dependencies solve the problem, but we shouldn't have to install those if we're not involved in phpactor's developement... So the solution is either to port the dependency in the require block, or not depend on such dependencies at all (or make them optionnal).

**Comment by dantleech** [comment] 2021-05-25 12:35
hmm, caused by [this](https://github.com/phpactor/phpactor/pull/1267) and fixed by [this](https://github.com/phpactor/rpc-extension/pull/14) so probalby need to bump that dep

**Comment by dantleech** [comment] 2021-05-25 12:38
Bumped the dep and pushed to master, should fix it

**Closed by dantleech** 2021-05-25 12:38 UTC

**Comment by Taluu** [comment] 2021-05-25 12:42
Yep, it fixed it. :}
