### ISSUE TITLE
The percentage must be an integer comprised between 0 and 100

### ISSUE THREAD

**Issue by calebdw** [phpactor/phpactor#2609] opened 2024-03-18 16:15 UTC
Hello!

I'm getting the following error:

Error in service "indexer" "Phpactor\Extension\LanguageServerIndexer\Handler\IndexerHandler:Phpactor\LanguageServer\Core\Service\{closure}": The percentage must be an integer comprised between 0 and 100.

I'm not sure if this has to do with #2412 or not...

Thanks!

**Comment by przepompownia** [comment] 2024-03-18 19:01
Duplicate of #2607

**Comment by dantleech** [comment] 2024-03-18 20:18
is it a duplicate? the referenced PR is about hanging, this one is about a specific error?

this is related to this code: https://github.com/phpactor/language-server/blob/master/lib/Core/Server/Client/WorkDoneProgressClient.php#L81

(`vendor/phpactor/language-server/lib/Core/Server/Client/WorkDoneProgressClient.php`)

could you maybe add change it to:
```
            throw new InvalidArgumentException(sprintf(
                'The percentage must be an integer comprised between 0 and 100. Got %d', $percentage,
            ));
```

and see what number it's getting and if possible see how it's getting that number?

**Comment by dantleech** [comment] 2024-03-18 21:09
Ignore the above, it's because with PHAR indexing we return more "file notifications" than there are real files (I.e. one phar = many files)

**Comment by calebdw** [comment] 2024-03-18 21:10
Yeah, it just showed 101%

**Comment by dantleech** [comment] 2024-03-18 21:53
Quick fix isto just yield the PHAR file in the IndexJob class

**Comment by dantleech** [comment] 2024-03-18 22:09
i've pushed a quickfix, the real solution is for me not to be so lazy and implement this properly :roll_eyes:

**Closed by dantleech** 2024-03-18 22:09 UTC
