### ISSUE TITLE
Import not working for phpdoc

### ISSUE THREAD

**Issue by Herz3h** [phpactor/phpactor#1106] opened 2020-09-30 09:50 UTC
With this code (Pipe character is the cursor position, right before Request btw):

```php
        /** @var |Request $request */
        $request = $subject;
```

And this command:

`:call phpactor#UseAdd()`

Menu is shown but selecting any option doesn't add the import in the use section.

However if I do it on this code it adds the import selected from the menu:
```php
$request = new |Request();
```

This used to work before. 

> Not directly related, but I've tried the coc-phpactor extension, and it behaves same, but only shows 3 import options in the menu instead of all.

Neovim: 0.4.3
phpactor: 0.16.2

**Comment by elythyr** [comment] 2020-09-30 10:04
I also had this issue, the import does not work in comments anymore.
That's a relatively recent regression.

**Comment by elythyr** [comment] 2020-10-10 12:45
I have some trouble updating all the packages right now so I could not test it yet.
But I think the problem come from the commit [9df5d232](https://github.com/phpactor/code-transform/blame/41071cee6da50937e68e8a6391d03719e2e649c7/lib/Adapter/TolerantParser/Refactor/TolerantImportName.php#L52)
```diff
@@ -45,12 +48,16 @@ class TolerantImportClass implements ImportClass
         $sourceNode = $this->parser->parseSourceFile($source);
         $node = $sourceNode->getDescendantNodeAtPosition($offset);
 
+        if (!$node instanceof NamespacedNameInterface) {
+            return TextEdits::none();
+        }
+
```
Since the offset is in some phpdoc the reflector does not recognize it, I'll try to confirm that when the packages will be installed.
@dantleech do you remember why you added this check ?

**Comment by dantleech** [comment] 2020-10-10 14:39
Thanks for finding the issue - probably introduced when introducing PHPStan - so any change to fix it would be welcome.

**Comment by elythyr** [comment] 2020-10-10 15:35
OK I will try to find a solution, by the way my issues come from phpstan
The `.git` folder is about 800M and multiply by the number of packages using it it my partition dedicated to source code was maxed out ><

**Comment by dantleech** [comment] 2020-10-10 18:17
:grimacing: if it's from Phpactor's packages they should all probably have `prefer-stable`

**Comment by elythyr** [comment] 2020-10-11 08:35
You think it will solve the issue ?
I'll gave it a try.

**Comment by dantleech** [comment] 2020-10-11 09:10
`prefer-stable` should ensure that the archived version is downloaded if a stable version exists satisfying the version constraints - it won't checkout the git repo.

**Comment by elythyr** [comment] 2020-10-11 10:01
Well, seems to work !
For the `cdoe-transform` package with the `~0.12.0` version I get 32M
For the `cdoe-builder` package with the `~0.11.0` version I get 3.9M

The size difference seems to be because the latest version is shipped with two executables, but it's a lot more manageable as it is: )

**Closed** 2020-11-01 10:45 UTC

**Comment by Herz3h** [comment] 2020-11-17 08:55
The bug seems to be still there, I've updated to latest version, and still in some cases, it doesn't autoimport. 

It shows `Imported class "MyClass\Whatever"` in the status bar, but nothing is being added to the use list.

**Comment by elythyr** [comment] 2020-11-17 08:59
Strange, I don't have any issue on my side.
Without a reliable way to reproduce we won't be able to identify the issue, if you ever have the problem again can you try to create the minimum necessary code to reproduce ?

**Comment by Herz3h** [comment] 2020-11-17 10:58
Here is a [reproduction repo](https://github.com/Herz3h/test-phpactor-import/blob/main/src/Controller/TestController.php#L16) try to call `:call phpactor#UseAdd()` with cursor on TestEntity, nothing happens besides a message being shown in status bar.

**Comment by pottink** [comment] 2020-11-17 12:01
> The bug seems to be still there, I've updated to latest version, and still in some cases, it doesn't autoimport.
> 
> It shows `Imported class "MyClass\Whatever"` in the status bar, but nothing is being added to the use list.

Agree, same here. I also updated to the latest version.

**Comment by elythyr** [comment] 2020-11-17 13:02
> Here is a [reproduction repo](https://github.com/Herz3h/test-phpactor-import/blob/main/src/Controller/TestController.php#L16) try to call `:call phpactor#UseAdd()` with cursor on TestEntity, nothing happens besides a message being shown in status bar.

Thanks a lot, just tried it and it worked.
What is the result of:
```sh
cd <your-project>
phpactor status
```

Well, I should pay more attention:
> phpactor: 0.16.2

Seems that you're on master ? `phpactor --version` shows `Phpactor dev-develop@7f73078a6771549895aa18714d11cbe08bc75899` for me

And indeed this is a bug on master, it was fix on develop recently.

**Comment by dantleech** [comment] 2020-11-17 13:48
Should probably try and push a new release (17) - last one was over four months ago :scream:

**Comment by Herz3h** [comment] 2020-11-17 16:31
@elythyr  Got this in my vimrc, so it's probably pointing to master or latest release:

`Plug 'phpactor/phpactor', {'for': 'php', 'do': 'composer install'}`

**Comment by dantleech** [comment] 2020-11-17 17:02
@Herz3h try `"Plug 'phpactor/phpactor' ,  {'branch': 'develop','do': 'composer install', 'for': 'php'}`
