### ISSUE TITLE
Can't use phpactor on vim if a vendor is a symlink

### ISSUE THREAD

**Issue by Taluu** [phpactor/phpactor#396] opened 2018-04-10 13:18 UTC
If I have a vendor that is a symlink outside my project, it seems thar phpactors hangs with a fatal error :

> Error from Phpactor: Trying to create descendant from absolute path "/home/talus/dev/Dep/src" that does not lie within context path "/home/talus/dev/project"

As in my vendor directory, I did the following :

```
$ cd vendor/provider
$ rm -rf dependency
$ ln -s ~/dev/Dep dependency
```

With this, I'm always getting said error on each phpactor vim command.

**Comment by dantleech** [comment] 2018-04-10 20:37
Hmm, can't reproduce. Can you provide a stack trace?

**Comment by Taluu** [comment] 2018-04-10 20:50
Should I find it in the logs ?

**Comment by Taluu** [comment] 2018-04-10 21:06
Hum, nevermind, can't reproduce it either... I could do it for 2 different projects, in which the vendor pointed on the same external vendor earlier, but now it seems I can't. Maybe it's because my symlinks were weird...

**Comment by dantleech** [comment] 2018-04-11 06:52
You can use the `rpc.store_replay: true` option and then run `$ phpactor rpc --replay --verbose` from the command line - this will replay the last request from e.g. VIM.

**Comment by dantleech** [comment] 2018-04-11 10:50
Actually getting this myself today :thinking:

**Comment by dantleech** [comment] 2018-04-11 11:15
Strange that this started to happen now, but was because `realpath` for resolving the composer path to the original path, causing the out-of-bounds error. Fixed in https://github.com/phpactor/phpactor/commit/f1f6f1366ec23588dec3eeef49549330d0e3afb3

**Comment by dantleech** [comment] 2018-04-11 11:15
in `develop` at least

**Closed by dantleech** 2018-04-11 11:15 UTC
