### ISSUE TITLE
Support @mixin

### ISSUE THREAD

**Issue by ciricode** [phpactor/phpactor#1642] opened 2022-05-24 09:33 UTC
```php
class ClassA
{
    public function methodOfClassA(): string
    {
        return 'This is classA';
    }
}

/** @mixin ClassA */
class ClassB
{
    public function methodOfClassB(): string
    {
        return 'This is classB';
    }

    public function __call($name, $arguments)
    {
        (new ClassA())->$name(...$arguments);
    }
}
```

**Comment by dantleech** [comment] 2022-05-24 10:09
closing as duplicate of #990 but have pinned the issue to priorise it.

**Closed by dantleech** 2022-05-24 10:09 UTC
