### ISSUE TITLE
Performance: Can we reduce the overhead ReflectionCollection ->filter ?

### ISSUE THREAD

**Issue by mamazu** [phpactor/phpactor#2197] opened 2023-04-10 15:59 UTC
I have checked the performance of the `AnalyzerBench` to see why it is so slow. According to XDebug there is some considerable time spend in the `Phpactor\WorseReflection\Core\Reflection\Collection\AbstractReflectionCollection->filter` namely the `array_filter` function.

Which in this case makes sense. If you only want to have the first element of a huge array, you still have to filter it all the way though.

My suggestion would be to use some kind of lazy generator that only generates the elements it needs.

**Comment by dantleech** [comment] 2023-04-22 07:54
Can we get a profile for this or rather illustrate the issue? The solution may not be to implement a generator.

**Comment by mamazu** [comment] 2023-04-22 14:29
Okay, my reasoning behind this proposal was the following. I have profiled the `AnalyserBench` Benchmark and this was the result:

![image](https://user-images.githubusercontent.com/14860264/233790519-86774169-e6b6-435d-90f9-96be042c9fa2.png)

The two most intense function in there are the `array_filter` (which is called from the `ClassLikeMemberCollection->filter` function) and `ReflectionClassLikeCollection::fromNode`.

While there isn't much we can do in the later case, because almost the entire time of the of the `fromNode` function is spend on `getDescendantNodes` (part of the php parser) we could do something about the class like member collection.

**Comment by dantleech** [comment] 2023-06-10 20:00
I don't get a bottleneck on `array_filter`- perhaps it has been fixed? reflection could be more efficient, but I can't cause create significant improvements with memoization, closing for now - there are performance issues but I'm not sure they are caused by array_filter.

**Closed by dantleech** 2023-06-10 20:00 UTC
Labels: Performance

**Comment by mamazu** [comment] 2023-06-10 20:26
Just out of curiosity which php version did you use for your trace? I was using 8.2 maybe this is a regression in the PHP runtime.
