### ISSUE TITLE
In Prophecy tests there are too many "Quick fix" actions to be useful

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#2122] opened 2023-02-28 19:08 UTC
All of the listed "missing" method are prophesized. ~Shouldn't the new "Prophecy" extension help with this?~
<img width="871" alt="image" src="https://user-images.githubusercontent.com/12109622/221954301-1f577de4-b352-465e-b381-7113ceca6263.png">
Edit: Sorry,  I thought I saw a Prophecy extension prompt.

**Comment by dantleech** [comment] 2023-02-28 19:39
It should if you documented the properties properly... You can check the tests

**Comment by BladeMF** [comment] 2023-02-28 19:41
can you link the test please?

**Comment by dantleech** [comment] 2023-02-28 19:49
was away from keyboard...

![image](https://user-images.githubusercontent.com/530801/221962963-83f328cd-35f9-4dbb-b5a3-141d477f0285.png)

**Comment by BladeMF** [comment] 2023-02-28 19:52
I see. I am not using properties at all. I do all the prophesizing in the fluent syntax when injecting, e.g.
```php
$this->prophesize(MyClass::class)
  ->myMethod()
    ->shouldBeCalled()
    ->willReturn(5)
    ->getObjectProphecy()
  ->reveal()
```

**Comment by dantleech** [comment] 2023-02-28 20:27
against the odds it works for me:

![image](https://user-images.githubusercontent.com/530801/221970684-80c43842-9030-4e68-b6bd-aae7020d586f.png)

**Comment by dantleech** [comment] 2023-02-28 20:33
you could try and add a reproducing case here:

https://github.com/phpactor/phpactor/blob/b917956977d216cc66ea30ba3f90df4e8922b24a/lib/Extension/Prophecy/Tests/Integration/WorseReflection/ProphecyMemberContextResolverTest.php#L13

or perhaps share the code which is failing

**Comment by BladeMF** [comment] 2023-03-01 07:28
Ha! I will sure do. Is possible though that I may have not setup things properly? I did reindex the project, and I am using the latest version, did composer install, and I've answered "yes" to all the prompts for extensions except for CS fixer which for some reason fails but I haven't had the time to debug. Anything else I should be doing?

**Comment by dantleech** [comment] 2023-03-01 08:42
You'll need to restart Phpactor after it updates the config, but otherwise that's it. If PHP-CS-Fixer fails and you're using 8.2 you may want to do this:

```
    "language_server_php_cs_fixer.env": {
        "XDEBUG_MODE": "off",
        "PHP_CS_FIXER_IGNORE_ENV": true
    },
```

(i should probably add that to the autoconfig)

**Comment by BladeMF** [comment] 2023-03-01 09:03
Ah, yes. I am indeed using 8.2 on this project.

**Comment by dantleech** [comment] 2023-03-01 10:18
I just pushed a fix to master to make it ignore the PHP version by default, so that should be fine now.

**Comment by BladeMF** [comment] 2023-03-03 15:44
I think I saw the problem. It's the second call that's not working:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/12109622/222763581-ca657cba-0fbb-4bd8-8dc2-224a244e089c.png">
The error is `Method "dumpFile" does not exist on class "Prophecy\Prophecy\ObjectProphecy"`

**Comment by dantleech** [comment] 2023-03-03 18:20
Hm ok so chaining issue I guess

**Comment by BladeMF** [comment] 2023-03-03 18:43
It would appear so, yes. I am guessing it is because it is easier to have `$this->prophesize(class-name)` of type `class-name`, than to find the actual prophecy whose `MethodProphecy` is being created when you find `getObjectProphecy`. Because imagine even this case:
```php
$method = $this->prophesize(SomeClass:class)->someMethod()->shouldBeCalled();
$objectProphecy = $method->getObjectProphecy();
```
The question is what type is `$objectProphecy`? The correct type is `ObjectProphecy<SomeClass>`, but without having a `MethodProphecy<SomeClass>` type I don't see how will that work.

**Comment by dantleech** [comment] 2023-03-03 18:54
I think it does work like that, bit will need to check

**Comment by dantleech** [comment] 2023-03-03 20:09
We do return a `MethodProphecy<class-type>`, however the stub does not return the templateed type:

https://github.com/phpactor/phpactor/blob/07e3ce1fe809c03e1efb771dd80a19a10bef179f/lib/Extension/Prophecy/stubs/Prophecy.stub#L277-L284

and what's more, it doesn't seem to work when adding the `ObjectProphecy<T>` so need to investigate that.

**Comment by dantleech** [comment] 2023-03-03 22:11
woudl this fix it https://github.com/phpactor/phpactor/pull/2127  ?

**Comment by dantleech** [comment] 2023-03-04 14:25
should now be fixed by the above :crossed_fingers:

**Closed by dantleech** 2023-03-04 14:25 UTC
