### ISSUE TITLE
Import class does not pick up typed properties

### ISSUE THREAD

**Issue by BladeMF** [phpactor/phpactor#1310] opened 2021-07-15 12:31 UTC
In this example:

```php
class ListTest extends KernelTestCase
{
	private Renderer $renderer;
	private Environment $twig;
```
`Renderer` and `Environment`  are not picked up as types for importing. If I say, for example, use the same classes in a method like `Renderer::class`, they are then suggested.

**Comment by dantleech** [comment] 2022-05-04 16:40
actually i can't reproduce this, assuming it was fixed in the meantime :)

**Closed by dantleech** 2022-05-04 16:40 UTC
Labels: bug
