### ISSUE TITLE
[neovim] 0.5 URI must contain a scheme to find workspace symbols using nvim-lspconfig or Telescope command

### ISSUE THREAD

**Issue by afranioce** [phpactor/phpactor#1313] opened 2021-07-19 20:08 UTC
When I execute the command `Telescope lsp_workspace_symbols query=something` or `:lua vim.lsp.buf.workspace_symbol()` returns a error **URI must contain a scheme**

![Peek 2021-07-19 17-07](https://user-images.githubusercontent.com/893768/126220669-06bc23f6-5574-462a-823f-6b2297e5fc0b.gif)

**Comment by greg0ire** [comment] 2021-11-24 07:41
I've experienced this too… the issues goes away when I wrap the query with quotes, but then it finds nothing :sweat_smile:

**Comment by DanielSiepmann** [comment] 2022-03-22 13:38
I receive the "same". I use Telescope in order to execute a language server command "Generate method".
There is no error displayed, but it is shown in the LSP log:
```json
OUT:
{
    "id": "52ca9abb-6c21-40fa-ba43-e6887c65649c",
    "method": "workspace\\/applyEdit",
    "params": {
        "edit": {
            "changes": {
                "\\/home\\/daniels\\/Projects\\/company\\/customer\\/…\\/Classes\\/Tca\\/ComparisonCards\\/DataHandlerHook.php": [
                    {
                        "range": {
                            "start": {
                                "line": 96,
                                "character": 5
                            },
                            "end": {
                                "line": 96,
                                "character": 5
                            }
                        },
                        "newText": "\
                        "
                    },
                    {
                        "range": {
                            "start": {
                                "line": 96,
                                "character": 5
                            },
                            "end": {
                                "line": 96,
                                "character": 5
                            }
                        },
                        "newText": "\
                        private function findRelatedUids(int $uid)\
                        {\
                        }"
                    }
                ]
            },
            "documentChanges": null
        },
        "label": "Generate method"
    },
    "jsonrpc": "2.0"
}

IN:
{
    "jsonrpc": "2.0",
    "result": {
        "applied": false,
        "failureReason": "...eovim-unwrapped-0.6.1\\/share\\/nvim\\/runtime\\/lua\\/vim\\/uri.lua:105: URI must contain a scheme: \\/home\\/daniels\\/Projects\\/company\\/customer\\/…\\/Classes\\/Tca\\/ComparisonCards\\/DataHandlerHook.php"
    },
    "id": "52ca9abb-6c21-40fa-ba43-e6887c65649c"
}
```

Used Neovim 0.6.1 and phpactor a7d46e12b70fcfb424a3eac045d5019a5b12de83

It works when I use the phpactor vim builtin call to generate the method. So maybe an incompatibility related to [telescope](https://github.com/nvim-telescope/telescope.nvim)?

**Comment by dantleech** [comment] 2022-03-24 20:37
r.e. the generate method: I didn't get an error, but also the refactoring didn't get applied, fixed in: https://github.com/phpactor/phpactor/pull/1378

I could not reproduce the original issue with Telescope, so closing. Reopen if it's still an issue.

**Closed by dantleech** 2022-03-24 20:37 UTC

**Comment by afranioce** [comment] 2022-03-24 22:55
Nice, I just test and works as expected, thanks
